"""Provider ports (S0 §3) — the only interfaces `app/services/` may depend on for outside-world
calls. Each `Protocol` gets a real adapter and a fake adapter, tested by the identical contract
suite (`tests/contract/`). Orchestrator-owned — escalate rather than editing directly.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    import uuid
    from datetime import date, datetime

    from app.core.money import Money, Price, Units


# --- KycPort (S2 §4/§5.1, ADR 9 — Stripe Identity) --------------------------------------------


@dataclass(frozen=True, slots=True)
class KycSessionHandle:
    """What `KycPort.create_verification_session` hands back to start the hosted flow (S2 §6)."""

    provider_session_id: str
    client_secret: str


class KycPort(Protocol):
    """The verdict arrives as a webhook through `inbound_event` intake (S2 §4); this only starts a session."""

    def create_verification_session(self, *, customer_id: str) -> KycSessionHandle: ...

    def retrieve_verification_session(self, *, provider_session_id: str) -> str:
        """The provider's current raw status string for an existing session -- the safety net for
        when a verdict webhook hasn't arrived yet (or, in local dev, can't reach the app at all)."""
        ...


# --- BankPort (S2 §5.1, FR-4/41/42/43 — Plaid) ------------------------------------------------


@dataclass(frozen=True, slots=True)
class BankLinkHandle:
    """What `BankPort.exchange_public_token` hands back after linking (S2 §3.3/§5.1). `access_token`
    is plaintext exactly once, at exchange time — caller encrypts before it touches `bank_link`."""

    plaid_item_id: str
    access_token: str


@dataclass(frozen=True, slots=True)
class LinkTokenHandle:
    """What `BankPort.create_link_token` hands back to open Plaid Link client-side."""

    link_token: str
    expiration: datetime


class BankPort(Protocol):
    def create_link_token(self, *, client_user_id: str) -> LinkTokenHandle: ...

    def exchange_public_token(self, *, public_token: str) -> BankLinkHandle: ...


# --- BrokerPort (S3 §6, ADR 21/22 — Alpaca Paper Trading) --------------------------------------


class OrderSide(StrEnum):
    BUY = "buy"
    SELL = "sell"


@dataclass(frozen=True, slots=True)
class BrokerOrderHandle:
    """Confirms the broker actually accepted the order (S3 §4)."""

    broker_order_id: str
    client_order_id: str


class BrokerPort(Protocol):
    def submit_order(
        self,
        *,
        client_order_id: str,
        symbol: str,
        side: OrderSide,
        quantity: str,
    ) -> BrokerOrderHandle:
        """`client_order_id` is generated by the caller (S3 §3.1/§5), never produced by this port."""
        ...


# Fills arrive over Alpaca's `trade_updates` websocket (ADR 22), not a BrokerPort method — see
# `integrations/alpaca/trade_updates_consumer.py`.


# --- MarketDataPort (S4 §4 — Alpaca market data) -----------------------------------------------


@dataclass(frozen=True, slots=True)
class CloseQuote:
    security_symbol: str
    market_date: date
    close_price: Price


class MarketDataPort(Protocol):
    def get_close(self, *, symbol: str, market_date: date) -> CloseQuote | None:
        """`None` means the provider has no close yet; caller handles missing-vs-stale (S4 §6)."""
        ...


# --- CalendarPort (S4 §3.4, ADR 12 — Alpaca trading calendar) ----------------------------------


@dataclass(frozen=True, slots=True)
class TradingDayInfo:
    market_date: date
    is_trading_day: bool
    session_open_at: datetime | None
    session_close_at: datetime | None


class CalendarPort(Protocol):
    """Populates `market_calendar_cache` (S4 §3.4). Distinct from `app/core/clock.py`'s
    `TradingCalendar`, which queries that cache — connected via the cache, not directly."""

    def get_trading_day(self, *, market_date: date) -> TradingDayInfo: ...


# --- CustodianFilePort (S7 §3/§9 — the morning custodian file, simulated in v1) ---------------


class CustodianTransactionType(StrEnum):
    TRADE = "trade"
    DIVIDEND = "dividend"
    DEPOSIT = "deposit"
    WITHDRAWAL = "withdrawal"
    FEE = "fee"


@dataclass(frozen=True, slots=True)
class CustodianPositionRow:
    """`positions.csv` (S7 §3.1) — one row per `(customer_id, security_id)` held."""

    customer_id: uuid.UUID
    security_id: uuid.UUID
    quantity: Units
    as_of_date: date


@dataclass(frozen=True, slots=True)
class CustodianCashRow:
    """`cash.csv` (S7 §3.2) — the custodian's view of one customer's settled cash."""

    customer_id: uuid.UUID
    settled_cash: Money
    as_of_date: date


@dataclass(frozen=True, slots=True)
class CustodianTransactionRow:
    """`transactions.csv` (S7 §3.3) — one row per custodian-side transaction."""

    custodian_transaction_id: str
    customer_id: uuid.UUID | None
    security_id: uuid.UUID | None
    transaction_type: CustodianTransactionType
    amount_money: Money
    quantity: Units | None
    effective_date: date


@dataclass(frozen=True, slots=True)
class CustodianFileSet:
    """The three files one morning run delivers (S7 §3). `is_simulated` is FR-33's structural
    "clearly labelled" tag."""

    positions: list[CustodianPositionRow]
    cash: list[CustodianCashRow]
    transactions: list[CustodianTransactionRow]
    is_simulated: bool


class CustodianFilePort(Protocol):
    """The morning custodian file source (S7 §3). No real custodian feed is contracted yet (S7 §12)."""

    def fetch_files(self, *, market_date: date) -> CustodianFileSet: ...


# --- PaymentPort (S10 §5/§7, ADR 10 — Stripe Billing) -----------------------------------------


@dataclass(frozen=True, slots=True)
class PaymentMethodHandle:
    """What `PaymentPort.attach_payment_method` hands back (S10 §7): the mapped Stripe customer
    and the payment method now attached as default."""

    stripe_customer_id: str
    stripe_payment_method_id: str


@dataclass(frozen=True, slots=True)
class ChargeHandle:
    """What a successful `PaymentPort.charge` hands back. `status` is the provider's raw status
    string; interpreting it into `FeeChargeStatus` is `FeeChargeService`'s job, not the port's."""

    stripe_charge_id: str
    status: str


class PaymentDeclinedError(RuntimeError):
    """The provider synchronously refused the charge — distinct from a transport/config failure.
    `FeeChargeService`/`DunningService` catch this to start/continue dunning (S10 §5)."""

    def __init__(self, *, reason: str) -> None:
        super().__init__(f"payment declined: {reason}")
        self.reason = reason


class PaymentPort(Protocol):
    """Stripe Billing, never Alpaca cash (ADR 10). `charge()` is synchronous, off-session; an
    async webhook confirmation also arrives via `inbound_event` intake (S10 §7)."""

    def attach_payment_method(
        self, *, stripe_customer_id: str | None, customer_email: str, payment_method_id: str
    ) -> PaymentMethodHandle: ...

    def charge(
        self,
        *,
        stripe_customer_id: str,
        stripe_payment_method_id: str,
        amount: Money,
        idempotency_key: str,
    ) -> ChargeHandle:
        """Raises `PaymentDeclinedError` on decline. `idempotency_key` must be stable across
        retries (S10 §5: `fee_charge.id`) so a retried outbox call never double-charges."""
        ...
