"""Provider ports (S0 §3) — the only interfaces `app/services/` may depend on for outside-world
calls. Each `Protocol` here gets a real adapter (the actual provider) and a fake adapter (in
`integrations/fake/`), tested by the identical contract suite (`backend/CLAUDE.md`'s four-layer
harness, `tests/contract/`) so a fake cannot silently drift from the provider it stands in for.

`services/` depends on these `Protocol`s, never a concrete adapter (S0 §3's dependency rule,
enforced by `lint-imports`) — Dependency Inversion, and what lets a test substitute a fake with no
import of a real provider SDK at all.

Orchestrator-owned (S0 build plan §4): written once, up front, so parallel engineers building
against different ports never collide on this shared file. A port's shape may need a real
follow-up change once an engineer actually implements against it — escalate that rather than
editing this file directly, since another track may depend on the same Protocol.

Only the ports Wave 4 (S2 funding, S3 orders, S4 valuation) needs are defined here.
`PaymentPort` (Stripe Billing, S10) is added when S10 actually needs it — no speculative ports.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from datetime import date, datetime

    from app.core.money import Price


# --- KycPort (S2 §4/§5.1, ADR 9 — Stripe Identity) --------------------------------------------


@dataclass(frozen=True, slots=True)
class KycSessionHandle:
    """What `KycPort.create_verification_session` hands back to start the customer's hosted
    verification flow (S2 §6: `POST /identity/kyc-sessions` returns the client secret the
    frontend renders Stripe's flow with)."""

    provider_session_id: str
    client_secret: str


class KycPort(Protocol):
    """The verdict itself never arrives through this port — it arrives as a webhook through the
    shared `inbound_event` intake path (S2 §4), keyed on `provider_session_id`. This port only
    starts a session."""

    def create_verification_session(self, *, customer_id: str) -> KycSessionHandle: ...


# --- BankPort (S2 §5.1, FR-4/41/42/43 — Plaid) ------------------------------------------------


@dataclass(frozen=True, slots=True)
class BankLinkHandle:
    """What `BankPort.exchange_public_token` hands back after linking (S2 §3.3/§5.1).
    `access_token` is encrypted at rest by the caller before it touches `bank_link` — this port
    returns the plaintext value exactly once, at exchange time, per Plaid's own flow."""

    plaid_item_id: str
    access_token: str


class BankPort(Protocol):
    def exchange_public_token(self, *, public_token: str) -> BankLinkHandle: ...


# --- BrokerPort (S3 §6, ADR 21/22 — Alpaca Paper Trading) --------------------------------------


class OrderSide(StrEnum):
    BUY = "buy"
    SELL = "sell"


@dataclass(frozen=True, slots=True)
class BrokerOrderHandle:
    """Confirms the broker actually accepted the order (S3 §4: `submitted` only fires once this
    call succeeds — an order never shows `submitted` while the broker never received it)."""

    broker_order_id: str
    client_order_id: str


class BrokerPort(Protocol):
    def submit_order(
        self,
        *,
        client_order_id: str,
        symbol: str,
        side: OrderSide,
        quantity: str,
    ) -> BrokerOrderHandle:
        """`client_order_id` is generated by the caller (S3 §3.1/§5 — deterministic, derived from
        `order.id`, never regenerated on retry) and passed in, never produced by this port."""
        ...


# Fills arrive over Alpaca's `trade_updates` websocket, not a request/response call (ADR 22) —
# deliberately not modeled as a `BrokerPort` method. The always-on consumer that reads that
# stream and feeds it into `inbound_event` is its own integration module
# (`integrations/alpaca/trade_updates_consumer.py`, S3's to design) — a genuinely different shape
# than the synchronous provider calls above, not a port method to force into this Protocol.


# --- MarketDataPort (S4 §4 — Alpaca market data) -----------------------------------------------


@dataclass(frozen=True, slots=True)
class CloseQuote:
    security_symbol: str
    market_date: date
    close_price: Price


class MarketDataPort(Protocol):
    def get_close(self, *, symbol: str, market_date: date) -> CloseQuote | None:
        """`None` means the provider has no close for this symbol/date yet — the caller (S4
        `ValuationService`) is responsible for the missing-vs-stale distinction (S4 §6), not this
        port. This port reports what the provider actually said, honestly."""
        ...


# --- CalendarPort (S4 §3.4, ADR 12 — Alpaca trading calendar) ----------------------------------


@dataclass(frozen=True, slots=True)
class TradingDayInfo:
    market_date: date
    is_trading_day: bool
    session_open_at: datetime | None
    session_close_at: datetime | None


class CalendarPort(Protocol):
    """Populates `market_calendar_cache` (S4 §3.4). Distinct from `app/core/clock.py`'s
    `TradingCalendar` Protocol, which `MarketClock` queries against the *cached* data —
    `CalendarPort` is the provider-facing fetch, `TradingCalendar` is the pure in-process query
    interface over what's already cached. A repository-backed adapter implementing
    `TradingCalendar` reads from `market_calendar_cache` this port populates; the two are
    connected by that cache, not by one calling the other directly."""

    def get_trading_day(self, *, market_date: date) -> TradingDayInfo: ...
