"""Provider ports (S0 §3) — the only interfaces `app/services/` may depend on for outside-world
calls. Each `Protocol` here gets a real adapter (the actual provider) and a fake adapter (in
`integrations/fake/`), tested by the identical contract suite (`backend/CLAUDE.md`'s four-layer
harness, `tests/contract/`) so a fake cannot silently drift from the provider it stands in for.

`services/` depends on these `Protocol`s, never a concrete adapter (S0 §3's dependency rule,
enforced by `lint-imports`) — Dependency Inversion, and what lets a test substitute a fake with no
import of a real provider SDK at all.

Orchestrator-owned (S0 build plan §4): written once, up front, so parallel engineers building
against different ports never collide on this shared file. A port's shape may need a real
follow-up change once an engineer actually implements against it — escalate that rather than
editing this file directly, since another track may depend on the same Protocol.

Only the ports Wave 4 (S2 funding, S3 orders, S4 valuation) needs are defined here.
`PaymentPort` (Stripe Billing, S10) is added when S10 actually needs it — no speculative ports.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    import uuid
    from datetime import date, datetime

    from app.core.money import Money, Price, Units


# --- KycPort (S2 §4/§5.1, ADR 9 — Stripe Identity) --------------------------------------------


@dataclass(frozen=True, slots=True)
class KycSessionHandle:
    """What `KycPort.create_verification_session` hands back to start the customer's hosted
    verification flow (S2 §6: `POST /identity/kyc-sessions` returns the client secret the
    frontend renders Stripe's flow with)."""

    provider_session_id: str
    client_secret: str


class KycPort(Protocol):
    """The verdict itself never arrives through this port — it arrives as a webhook through the
    shared `inbound_event` intake path (S2 §4), keyed on `provider_session_id`. This port only
    starts a session."""

    def create_verification_session(self, *, customer_id: str) -> KycSessionHandle: ...


# --- BankPort (S2 §5.1, FR-4/41/42/43 — Plaid) ------------------------------------------------


@dataclass(frozen=True, slots=True)
class BankLinkHandle:
    """What `BankPort.exchange_public_token` hands back after linking (S2 §3.3/§5.1).
    `access_token` is encrypted at rest by the caller before it touches `bank_link` — this port
    returns the plaintext value exactly once, at exchange time, per Plaid's own flow."""

    plaid_item_id: str
    access_token: str


@dataclass(frozen=True, slots=True)
class LinkTokenHandle:
    """What `BankPort.create_link_token` hands back to open Plaid Link client-side (frontend
    structural spec's onboarding wizard) — the client SDK cannot open at all without a
    server-minted `link_token`; this is the missing step before a caller ever has a
    `public_token` to hand `exchange_public_token` above."""

    link_token: str
    expiration: datetime


class BankPort(Protocol):
    def create_link_token(self, *, client_user_id: str) -> LinkTokenHandle: ...

    def exchange_public_token(self, *, public_token: str) -> BankLinkHandle: ...


# --- BrokerPort (S3 §6, ADR 21/22 — Alpaca Paper Trading) --------------------------------------


class OrderSide(StrEnum):
    BUY = "buy"
    SELL = "sell"


@dataclass(frozen=True, slots=True)
class BrokerOrderHandle:
    """Confirms the broker actually accepted the order (S3 §4: `submitted` only fires once this
    call succeeds — an order never shows `submitted` while the broker never received it)."""

    broker_order_id: str
    client_order_id: str


class BrokerPort(Protocol):
    def submit_order(
        self,
        *,
        client_order_id: str,
        symbol: str,
        side: OrderSide,
        quantity: str,
    ) -> BrokerOrderHandle:
        """`client_order_id` is generated by the caller (S3 §3.1/§5 — deterministic, derived from
        `order.id`, never regenerated on retry) and passed in, never produced by this port."""
        ...


# Fills arrive over Alpaca's `trade_updates` websocket, not a request/response call (ADR 22) —
# deliberately not modeled as a `BrokerPort` method. The always-on consumer that reads that
# stream and feeds it into `inbound_event` is its own integration module
# (`integrations/alpaca/trade_updates_consumer.py`, S3's to design) — a genuinely different shape
# than the synchronous provider calls above, not a port method to force into this Protocol.


# --- MarketDataPort (S4 §4 — Alpaca market data) -----------------------------------------------


@dataclass(frozen=True, slots=True)
class CloseQuote:
    security_symbol: str
    market_date: date
    close_price: Price


class MarketDataPort(Protocol):
    def get_close(self, *, symbol: str, market_date: date) -> CloseQuote | None:
        """`None` means the provider has no close for this symbol/date yet — the caller (S4
        `ValuationService`) is responsible for the missing-vs-stale distinction (S4 §6), not this
        port. This port reports what the provider actually said, honestly."""
        ...


# --- CalendarPort (S4 §3.4, ADR 12 — Alpaca trading calendar) ----------------------------------


@dataclass(frozen=True, slots=True)
class TradingDayInfo:
    market_date: date
    is_trading_day: bool
    session_open_at: datetime | None
    session_close_at: datetime | None


class CalendarPort(Protocol):
    """Populates `market_calendar_cache` (S4 §3.4). Distinct from `app/core/clock.py`'s
    `TradingCalendar` Protocol, which `MarketClock` queries against the *cached* data —
    `CalendarPort` is the provider-facing fetch, `TradingCalendar` is the pure in-process query
    interface over what's already cached. A repository-backed adapter implementing
    `TradingCalendar` reads from `market_calendar_cache` this port populates; the two are
    connected by that cache, not by one calling the other directly."""

    def get_trading_day(self, *, market_date: date) -> TradingDayInfo: ...


# --- CustodianFilePort (S7 §3/§9 — the morning custodian file, simulated in v1) ----------------


class CustodianTransactionType(StrEnum):
    TRADE = "trade"
    DIVIDEND = "dividend"
    DEPOSIT = "deposit"
    WITHDRAWAL = "withdrawal"
    FEE = "fee"


@dataclass(frozen=True, slots=True)
class CustodianPositionRow:
    """`positions.csv` (S7 §3.1) — one row per `(customer_id, security_id)` the custodian
    believes is held."""

    customer_id: uuid.UUID
    security_id: uuid.UUID
    quantity: Units
    as_of_date: date


@dataclass(frozen=True, slots=True)
class CustodianCashRow:
    """`cash.csv` (S7 §3.2) — the custodian's view of one customer's settled cash."""

    customer_id: uuid.UUID
    settled_cash: Money
    as_of_date: date


@dataclass(frozen=True, slots=True)
class CustodianTransactionRow:
    """`transactions.csv` (S7 §3.3) — one row per custodian-side transaction, keyed on the
    custodian's own transaction id."""

    custodian_transaction_id: str
    customer_id: uuid.UUID | None
    security_id: uuid.UUID | None
    transaction_type: CustodianTransactionType
    amount_money: Money
    quantity: Units | None
    effective_date: date


@dataclass(frozen=True, slots=True)
class CustodianFileSet:
    """The three files one morning run delivers (S7 §3), plus FR-33's structural
    "clearly labelled" tag: `is_simulated` travels with the file set itself, not just each fake
    adapter's naming convention, so `ReconciliationService` stamps it onto every
    `custodian_file_row` it writes without needing to know which adapter produced the set."""

    positions: list[CustodianPositionRow]
    cash: list[CustodianCashRow]
    transactions: list[CustodianTransactionRow]
    is_simulated: bool


class CustodianFilePort(Protocol):
    """The morning custodian file source (S7 §3). No real custodian feed is contracted yet (S7
    §12) — `integrations/fake/custodian_file_adapter.py`'s simulator is the only implementation
    today, exactly as NFR-12 anticipates ("simulated is fine")."""

    def fetch_files(self, *, market_date: date) -> CustodianFileSet: ...
