"""Add identity schemas and RLS

Revision ID: 85b775e8667c
Revises: fc5c875054d0
Create Date: 2026-09-05 09:48:22.203929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '85b775e8667c'
down_revision: Union[str, Sequence[str], None] = 'fc5c875054d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('kyc_status', sa.Enum('pending', 'approved', 'rejected', name='kycstatus'), nullable=False),
    sa.Column('account_approval_status', sa.Enum('pending', 'approved', 'rejected', name='accountapprovalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_table('staff',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('adviser', 'admin', name='staffrole'), nullable=False),
    sa.Column('totp_secret_encrypted', app.core.crypto.EncryptedText(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff'))
    )
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=True)
    # ### end Alembic commands ###

    op.execute("""
        ALTER TABLE customer ENABLE ROW LEVEL SECURITY;
        CREATE POLICY tenant_isolation ON customer
        USING (
            current_setting('app.role', true) IN ('adviser', 'admin')
            -- Postgres does not guarantee left-to-right short-circuit evaluation of OR operands
            -- (docs: "the order of evaluation of subexpressions is not defined"), so an
            -- adviser/admin session -- which leaves app.customer_id unset ('') -- can still hit
            -- the right-hand cast. NULLIF turns the empty string into NULL first: NULL::uuid is
            -- NULL (not an error), and `id = NULL` is NULL, which a USING clause treats as
            -- "exclude this row", not as "raise" -- so the role branch's OR still admits the row
            -- regardless of evaluation order (ADR 17).
            OR id = NULLIF(current_setting('app.customer_id', true), '')::uuid
        );
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON customer;")
    op.execute("ALTER TABLE customer DISABLE ROW LEVEL SECURITY;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    sa.Enum(name='kycstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='accountapprovalstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='staffrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
