"""add order.designated_lot_ids

Revision ID: cd483b78ace2
Revises: 24a90b294386
Create Date: 2026-09-08 20:34:28.910779

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cd483b78ace2'
down_revision: str | Sequence[str] | None = '24a90b294386'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('designated_lot_ids', postgresql.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'designated_lot_ids')
    # ### end Alembic commands ###
