"""add fee_charge unique constraint on customer and billing period

Revision ID: 44100b4c0cae
Revises: c4a1e9f7b3d5
Create Date: 2026-09-05 22:21:13.132444

F5 fix (S0 §10.1 audit): `FeeChargeService.create_pending_charge`'s idempotency was read-then-
insert only (`get_for_period` then `add`), so two concurrent or retried `MonthlyFeeChargeJob` runs
could race between the read and the insert and double-charge a customer for one billing period.
`fee_accrual` already gets this right (`uq_fee_accrual_customer_date`); this is the same DB-level
backstop for `fee_charge`, since `stripe_charge_id`'s existing uniqueness is nullable at creation
and does not close the gap.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44100b4c0cae'
down_revision: Union[str, Sequence[str], None] = 'c4a1e9f7b3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_fee_charge_customer_period', 'fee_charge', ['customer_id', 'billing_period_start', 'billing_period_end'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_fee_charge_customer_period', 'fee_charge', type_='unique')
    # ### end Alembic commands ###
