"""add S13 agent surface

Revision ID: 670073c5146c
Revises: 79c5ef5459fa
Create Date: 2026-09-06 04:24:00.412052

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '670073c5146c'
down_revision: str | Sequence[str] | None = '79c5ef5459fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_action_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('resolve_break', 'kyc_override', 'rebalance', name='agent_action_type'), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requesting_agent', sa.String(), nullable=False),
    sa.Column('justification', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'executed', 'execution_failed', name='agent_action_status'), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('execution_error', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'executed') OR (executed_at IS NOT NULL)", name=op.f('ck_agent_action_request_executed_requires_timestamp')),
    sa.CheckConstraint("(status <> 'execution_failed') OR (execution_error IS NOT NULL)", name=op.f('ck_agent_action_request_failure_requires_error')),
    sa.CheckConstraint("(status NOT IN ('approved','rejected')) OR (reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)", name=op.f('ck_agent_action_request_review_requires_reviewer')),
    sa.CheckConstraint('length(justification) > 0', name=op.f('ck_agent_action_request_justification_present')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_action_request'))
    )
    op.create_index('ix_agent_action_request_status_created', 'agent_action_request', ['status', 'created_at'], unique=False)
    op.create_table('staff_api_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_api_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_staff_api_token_token_hash'))
    )
    op.create_index(op.f('ix_staff_api_token_staff_id'), 'staff_api_token', ['staff_id'], unique=False)
    # ### end Alembic commands ###

    # Single-transition guard: pending -> {approved, rejected} -> {executed, execution_failed} (S13 §3.1, ADR 24).
    op.execute("""
        CREATE OR REPLACE FUNCTION agent_action_request_single_transition() RETURNS trigger AS $$
        BEGIN
          IF OLD.status = 'pending' THEN
            IF NEW.status NOT IN ('approved', 'rejected') THEN
              RAISE EXCEPTION
                'agent_action_request % may only move from pending to approved or rejected (got %)',
                OLD.id, NEW.status;
            END IF;
          ELSIF OLD.status = 'approved' THEN
            IF NEW.status NOT IN ('executed', 'execution_failed') THEN
              RAISE EXCEPTION
                'agent_action_request % may only move approved -> executed/execution_failed (got %)',
                OLD.id, NEW.status;
            END IF;
          ELSE
            RAISE EXCEPTION 'agent_action_request % is already terminal (%) and cannot be updated',
              OLD.id, OLD.status;
          END IF;
          IF NEW.action <> OLD.action
             OR NEW.arguments IS DISTINCT FROM OLD.arguments
             OR NEW.requesting_agent <> OLD.requesting_agent
             OR NEW.justification <> OLD.justification
             OR NEW.created_at <> OLD.created_at THEN
            RAISE EXCEPTION
              'agent_action_request % identifying fields are immutable once created (S13 section 3.1)',
              OLD.id;
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER agent_action_request_before_update
          BEFORE UPDATE ON agent_action_request
          FOR EACH ROW EXECUTE FUNCTION agent_action_request_single_transition();
    """)

    # Append-only in spirit (ADR 24): DELETE revoked for both runtime credentials.
    op.execute("REVOKE DELETE ON agent_action_request FROM trueup_app, trueup_worker;")

    # No RLS on either table (S13 §3.1/§3.2): access control is @requires_role on every route.


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS agent_action_request_before_update ON agent_action_request;")
    op.execute("DROP FUNCTION IF EXISTS agent_action_request_single_transition();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_api_token_staff_id'), table_name='staff_api_token')
    op.drop_table('staff_api_token')
    op.drop_index('ix_agent_action_request_status_created', table_name='agent_action_request')
    op.drop_table('agent_action_request')
    # ### end Alembic commands ###
    sa.Enum(name='agent_action_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='agent_action_type').drop(op.get_bind(), checkfirst=True)
