"""add profile fields to customer

Revision ID: 24a90b294386
Revises: 670073c5146c
Create Date: 2026-09-06 21:52:50.165475

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '24a90b294386'
down_revision: str | Sequence[str] | None = '670073c5146c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('display_name', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('phone', sa.String(length=16), nullable=True))
    op.add_column('customer', sa.Column('mailing_address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'mailing_address')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'display_name')
    # ### end Alembic commands ###
