"""add S12 §3 indexing strategy indexes

Revision ID: 79c5ef5459fa
Revises: 38096a12c976
Create Date: 2026-09-06 03:27:11.804112

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '79c5ef5459fa'
down_revision: str | Sequence[str] | None = '38096a12c976'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_account_customer_role', 'account', ['customer_id', 'role'], unique=False)
    op.create_index('ix_chat_message_session_created', 'chat_message', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_journal_entry_effective_date', 'journal_entry', ['effective_date'], unique=False)
    op.create_index('ix_journal_entry_recorded_at', 'journal_entry', ['recorded_at'], unique=False)
    op.create_index('ix_order_customer_status', 'order', ['customer_id', 'status'], unique=False)
    op.create_index('ix_posting_account_id', 'posting', ['account_id'], unique=False)
    op.create_index('ix_reconciliation_break_status_opened', 'reconciliation_break', ['status', 'opened_at'], unique=False)
    op.create_index('ix_tax_lot_customer_security_acquired', 'tax_lot', ['customer_id', 'security_id', 'acquired_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tax_lot_customer_security_acquired', table_name='tax_lot')
    op.drop_index('ix_reconciliation_break_status_opened', table_name='reconciliation_break')
    op.drop_index('ix_posting_account_id', table_name='posting')
    op.drop_index('ix_order_customer_status', table_name='order')
    op.drop_index('ix_journal_entry_recorded_at', table_name='journal_entry')
    op.drop_index('ix_journal_entry_effective_date', table_name='journal_entry')
    op.drop_index('ix_chat_message_session_created', table_name='chat_message')
    op.drop_index('ix_account_customer_role', table_name='account')
    # ### end Alembic commands ###
