"""add S1 ledger

Revision ID: a9f60402b7a1
Revises: 85b775e8667c
Create Date: 2026-09-05 11:48:33.363018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = 'a9f60402b7a1'
down_revision: Union[str, Sequence[str], None] = '85b775e8667c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('security_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('cash', 'customer_equity', 'position_units', 'position_cost', 'fees_expense', 'dividend_income', name='account_role'), nullable=False),
    sa.Column('dimension', sa.Enum('money', 'units', name='account_dimension'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.CheckConstraint("(role = 'cash' AND dimension = 'money') OR (role = 'customer_equity' AND dimension = 'money') OR (role = 'position_units' AND dimension = 'units') OR (role = 'position_cost' AND dimension = 'money') OR (role = 'fees_expense' AND dimension = 'money') OR (role = 'dividend_income' AND dimension = 'money')", name=op.f('ck_account_role_dimension')),
    sa.CheckConstraint("currency = 'USD'", name=op.f('ck_account_currency_usd')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account'))
    )
    op.create_table('customer_cash_lock',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_customer_cash_lock_customer_id_customer')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customer_cash_lock'))
    )
    op.create_table('journal_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('trade_buy', 'trade_sell', 'deposit', 'withdrawal', 'dividend', 'split', 'fee_adjustment', 'correction', name='journal_entry_type'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('supersedes_reason', sa.String(), nullable=True),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['inbound_event.id'], name=op.f('fk_journal_entry_source_event_id_inbound_event')),
    sa.ForeignKeyConstraint(['superseded_by'], ['journal_entry.id'], name=op.f('fk_journal_entry_superseded_by_journal_entry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entry')),
    sa.UniqueConstraint('source_event_id', name=op.f('uq_journal_entry_source_event_id'))
    )
    op.create_table('posting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('amount_money', app.core.money.MoneyType(precision=18, scale=4), nullable=True),
    sa.Column('quantity_units', app.core.money.UnitsType(precision=28, scale=6), nullable=True),
    sa.CheckConstraint('(amount_money IS NOT NULL AND quantity_units IS NULL) OR (amount_money IS NULL AND quantity_units IS NOT NULL)', name=op.f('ck_posting_exactly_one_dimension')),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_posting_account_id_account')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], name=op.f('fk_posting_journal_entry_id_journal_entry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting'))
    )
    op.create_table('settlement_obligation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount_money', app.core.money.MoneyType(precision=18, scale=4), nullable=False),
    sa.Column('expected_settlement_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', name='settlement_obligation_status'), server_default='pending', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_settlement_obligation_account_id_account')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], name=op.f('fk_settlement_obligation_journal_entry_id_journal_entry')),
    sa.ForeignKeyConstraint(['source_event_id'], ['inbound_event.id'], name=op.f('fk_settlement_obligation_source_event_id_inbound_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement_obligation')),
    sa.UniqueConstraint('source_event_id', name=op.f('uq_settlement_obligation_source_event_id'))
    )
    # ### end Alembic commands ###

    # RLS tenant isolation on every table carrying customer_id (S0 §7.3, ADR 17).
    op.execute("""
        ALTER TABLE account ENABLE ROW LEVEL SECURITY;
        CREATE POLICY tenant_isolation ON account
        USING (
            current_setting('app.role', true) IN ('adviser', 'admin')
            OR customer_id = NULLIF(current_setting('app.customer_id', true), '')::uuid
        );

        ALTER TABLE customer_cash_lock ENABLE ROW LEVEL SECURITY;
        CREATE POLICY tenant_isolation ON customer_cash_lock
        USING (
            current_setting('app.role', true) IN ('adviser', 'admin')
            OR customer_id = NULLIF(current_setting('app.customer_id', true), '')::uuid
        );

        ALTER TABLE posting ENABLE ROW LEVEL SECURITY;
        CREATE POLICY tenant_isolation ON posting
        USING (
            current_setting('app.role', true) IN ('adviser', 'admin')
            OR customer_id = NULLIF(current_setting('app.customer_id', true), '')::uuid
        );
    """)

    # posting_before_insert: denormalize customer_id and validate dimension (S1 §3.3).
    op.execute("""
        CREATE OR REPLACE FUNCTION posting_denormalize_and_validate() RETURNS trigger AS $$
        DECLARE
          acct RECORD;
        BEGIN
          SELECT customer_id, dimension INTO acct FROM account WHERE id = NEW.account_id;

          NEW.customer_id := acct.customer_id;

          IF acct.dimension = 'money' AND NEW.quantity_units IS NOT NULL THEN
            RAISE EXCEPTION 'posting.quantity_units set against a money-dimension account (%)', NEW.account_id;
          ELSIF acct.dimension = 'units' AND NEW.amount_money IS NOT NULL THEN
            RAISE EXCEPTION 'posting.amount_money set against a units-dimension account (%)', NEW.account_id;
          END IF;

          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER posting_before_insert
          BEFORE INSERT ON posting
          FOR EACH ROW EXECUTE FUNCTION posting_denormalize_and_validate();
    """)

    # ledger_balance: cross-row zero-sum invariant, deferred to COMMIT (S1 §6, ADR 17).
    op.execute("""
        CREATE OR REPLACE FUNCTION check_journal_entry_balance() RETURNS trigger AS $$
        DECLARE
          je_id uuid;
          total NUMERIC(18,4);
        BEGIN
          je_id := COALESCE(NEW.journal_entry_id, OLD.journal_entry_id);
          SELECT COALESCE(SUM(amount_money), 0) INTO total FROM posting WHERE journal_entry_id = je_id;
          IF total <> 0 THEN
            RAISE EXCEPTION 'journal_entry % postings do not sum to zero (got %)', je_id, total;
          END IF;
          RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;

        CREATE CONSTRAINT TRIGGER ledger_balance
          AFTER INSERT OR UPDATE OR DELETE ON posting
          DEFERRABLE INITIALLY DEFERRED
          FOR EACH ROW
          EXECUTE FUNCTION check_journal_entry_balance();
    """)

    # settlement_obligation: status transitions exactly once, pending -> terminal (S1 §6).
    op.execute("""
        CREATE OR REPLACE FUNCTION settlement_obligation_single_transition() RETURNS trigger AS $$
        BEGIN
          IF OLD.status <> 'pending' THEN
            RAISE EXCEPTION 'settlement_obligation % is already terminal (%) and cannot be updated',
              OLD.id, OLD.status;
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER settlement_obligation_before_update
          BEFORE UPDATE ON settlement_obligation
          FOR EACH ROW EXECUTE FUNCTION settlement_obligation_single_transition();
    """)

    # Append-only enforcement: revoke UPDATE/DELETE on journal_entry/posting for runtime roles (S1 §6, ADR 1).
    op.execute("""
        REVOKE UPDATE, DELETE ON journal_entry FROM trueup_app, trueup_worker;
        REVOKE UPDATE, DELETE ON posting FROM trueup_app, trueup_worker;
        REVOKE DELETE ON settlement_obligation FROM trueup_app, trueup_worker;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS settlement_obligation_before_update ON settlement_obligation;")
    op.execute("DROP FUNCTION IF EXISTS settlement_obligation_single_transition();")
    op.execute("DROP TRIGGER IF EXISTS ledger_balance ON posting;")
    op.execute("DROP FUNCTION IF EXISTS check_journal_entry_balance();")
    op.execute("DROP TRIGGER IF EXISTS posting_before_insert ON posting;")
    op.execute("DROP FUNCTION IF EXISTS posting_denormalize_and_validate();")

    op.execute("DROP POLICY IF EXISTS tenant_isolation ON posting;")
    op.execute("ALTER TABLE posting DISABLE ROW LEVEL SECURITY;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON customer_cash_lock;")
    op.execute("ALTER TABLE customer_cash_lock DISABLE ROW LEVEL SECURITY;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON account;")
    op.execute("ALTER TABLE account DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_obligation')
    op.drop_table('posting')
    op.drop_table('journal_entry')
    op.drop_table('customer_cash_lock')
    op.drop_table('account')
    # ### end Alembic commands ###
    sa.Enum(name='settlement_obligation_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='journal_entry_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='account_dimension').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='account_role').drop(op.get_bind(), checkfirst=True)
